services:
  - type: web
    name: funtasting
    env: php
    buildCommand: composer install --optimize-autoloader --no-dev && npm install && npm run build
    startCommand: php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        fromDatabase:
          name: funtasting-db
          property: connectionString

